simulate:
    exe: rt.R, rcauchy.R
    seed: R(1:5)
    params:
        n: 1000
        true_loc: 0, 1
    return: x, true_loc

transform:
    exe: qnorm.R
    params:
        x: $x
    return: x

estimate:
    exe: mean.R, median.R
    params:
        x: $x
    return: loc

mse:
    exe: MSE.R
    params:
        mean_est: $loc
        true_mean: $true_loc
    return: mse

DSC:
    run: simulate *
         (transform * estimate, estimate) *
         mse
    runtime:
        exe_path: .
        output: one_sample_location
