simulate:
    exec: datamaker.R
    seed: R(1:50)
    params:
        path: R(gsub("[[:space:]]", "", readChar($(fileName), file.info($(fileName))$size)))
        tissue: Adipose-Subcutaneous, (Adipose-Subcutaneous, Lung)
        Nsamp: 2, 10, 50
        Ngene: 10000
        breaksample: FALSE, TRUE
        .alias: args = RList()
    return: data, meta = R(data$meta)

simulate_normalized(simulate):
    params:
        voom.normalize: TRUE

simulate_partial_null(simulate):
    seed: R(1:5)
    params:
        tissue: (Adipose-Subcutaneous, Lung)
        breaksample: TRUE
        nullpi: 0.9

simulate_thinning(simulate):
    seed: R(1:5)
    params:
        tissue: Adipose-Subcutaneous
        breaksample: FALSE
        poisthin: TRUE

correction:
    exec: SVA.R, RUV.R, myrna.R
    params:
        data: $data
        .alias: args = RList()
    return: data

transform:
    exec: voom.R, quasibinom.R, edgeRglm.R, DESeq2glm.R
    params:
        data: $data
        .alias: args = RList()
    return: data

test:
    exec: edgeR.R, DESeq2.R, ash.R, jointash.R, limma.R
    params:
        data: $data
        .alias: args = RList()
        exec[1,2]:
            glm: TRUE, FALSE
        exec[5]:
            robust: TRUE, FALSE
    return: output

score:
    exec: score.R
    params:
        data: $meta
        work_dir: $output
    return: result

DSC:
    run: (simulate, simulate_normalized, simulate_partial_null, simulate_thinning) *
         (correction * transform * test[3:4], correction * transform[1] * test[5], test[1:2]) *
         score
    R_libs: github/stephens999/ashr, bioc/DESeq2, bioc/qvalue/3.2, mixash, github/mengyin/vash, limma,
            edgeR, RUVSeq, sva, data.table, DESeq
    exec_path: bin
    work_dir: gtex_total
    parameters:
        fileName: data_path.txt
