simulate:
    exe: datamaker.R
    seed: R(1:50)
    params:
        path: R(gsub("[[:space:]]", "", readChar($(fileName), file.info($(fileName))$size)))
        tissue: Adipose-Subcutaneous, (Adipose-Subcutaneous, Lung)
        Nsamp: 2, 10, 50
        Ngene: 10000
        voom.normalize: TRUE
        breaksample: FALSE, TRUE
        __alias__: RList(args)
    return: data, meta = FromRList(data, meta)

simulate_partial_null(simulate):
    seed: R(1:5)
    params:
        tissue: (Adipose-Subcutaneous, Lung)
        breaksample: TRUE
        nullpi: 0.9

simulate_thinning(simulate):
    seed: R(1:5)
    params:
        tissue: Adipose-Subcutaneous
        breaksample: FALSE
        poisthin: TRUE

correction:
    exe: SVA.R, RUV.R, myrna.R
    params:
        data: $data
        __alias__: RList(args)
    return: data

transform:
    exe: voom.R, quasibinom.R, edgeRglm.R, DESeq2glm.R
    params:
        data: $data
        __alias__: RList(args)
    return: data

test:
    exe: edgeR.R, DESeq2.R, ash.R, jointash.R, limma.R
    params:
        data: $data
        __alias__: RList(args)
        exe[1,2]:
            glm: TRUE, FALSE
        exe[5]:
            robust: TRUE, FALSE
    return: output

score:
    exe: score.R
    params:
        data: $meta
        output: $output
    return: result

DSC:
    run: (simulate, simulate_partial_null, simulate_thinning) *
         (correction * transform * test[3:4], correction * transform[1] * test[5], test[1:2]) *
         score
    runtime:
        R_libs: github/stephens999/ashr, bioc/DESeq2, bioc/qvalue/3.2, mixash, github/mengyin/vash, limma,
                edgeR, RUVSeq, sva, data.table, DESeq
        exe_path: bin
        output: gtex_total
        variables:
            fileName: data_path.txt