simulate:
    exe: datamaker.R
    seed: R(1:50)
    params:
        path: R(gsub("[[:space:]]", "", readChar($(fileName), file.info($(fileName))$size)))
        tissue: Adipose-Subcutaneous, (Adipose-Subcutaneous, Lung)
        Nsamp: 2, 10, 50
        Ngene: 10000
        voom.normalize: TRUE
        breaksample: FALSE, TRUE
        __alias__: RList(args)
    return: data, meta = FromRList(data, meta)

simulate_partial_null(simulate):
    seed: R(1:5)
    params:
        tissue: (Adipose-Subcutaneous, Lung)
        breaksample: TRUE
        nullpi: 0.9

simulate_thinning(simulate):
    seed: R(1:5)
    params:
        tissue: Adipose-Subcutaneous
        breaksample: FALSE
        poisthin: TRUE

SVA:
    exe: SVA.R
    params:
        data: $data
        __alias__: RList(args)
    return: data

RUV(SVA):
    exe: RUV.R

myrna(SVA):
    exe: myrna.R

voom(SVA):
    exe: voom.R

quasibinom(voom):
    exe: quasibinom.R

edgeRglm(SVA):
    exe: edgeRglm.R

DESeq2glm(SVA):
    exe: DESeq2glm.R

ash(SVA):
    exe: ash.R
    return: output

edgeR(ash):
    exe: edgeR.R
    params:
        glm: TRUE, FALSE

DESeq2(edgeR):
    exe: DESeq2.R

jointash(ash):
    exe: jointash.R

limma(ash):
    exe: limma.R
    params:
        robust: TRUE, FALSE

score:
    exe: score.R
    params:
        data: $meta
        output: $output
    return: result

DSC:
    run: (simulate, simulate_partial_null, simulate_thinning) *
         ((SVA, RUV, myrna) * (voom, quasibinom, edgeRglm, DESeq2glm) * (ash,jointash),
          (SVA, RUV, myrna) * voom * limma,
          (edgeR, DESeq2)) *
         score
    runtime:
        R_libs: github/stephens999/ashr, bioc/DESeq2, bioc/qvalue, mixash, github/mengyin/vash, limma,
                bioc/edgeR, RUVSeq, sva, data.table, DESeq
        exe_path: bin
        output: gtex_total
        variables:
            fileName: data_path.txt