simulate:
    exec: datamaker.R
    seed: R(1:50)
    params:
        path: R(gsub("[[:space:]]", "", readChar($(fileName), file.info($(fileName))$size)))
        tissue: Adipose-Subcutaneous, (Adipose-Subcutaneous, Lung)
        Nsamp: 2, 10, 50
        Ngene: 10000
        breaksample: FALSE, TRUE
        .alias: args = RList()
    return: data, meta = R(data$meta)

simulate_normalized(simulate):
    params:
        voom.normalize: TRUE

simulate_partial_null(simulate):
    seed: R(1:5)
    params:
        tissue: (Adipose-Subcutaneous, Lung)
        breaksample: TRUE
        nullpi: 0.9

simulate_thinning(simulate):
    seed: R(1:5)
    params:
        tissue: Adipose-Subcutaneous
        breaksample: FALSE
        poisthin: TRUE

SVA:
    exec: SVA.R
    params:
        data: $data
        .alias: args = RList()
    return: data

RUV(SVA):
    exec: RUV.R

myrna(SVA):
    exec: myrna.R

voom(SVA):
    exec: voom.R

quasibinom(voom):
    exec: quasibinom.R

edgeRglm(SVA):
    exec: edgeRglm.R

DESeq2glm(SVA):
    exec: DESeq2glm.R

ash(SVA):
    exec: ash.R
    return: output

edgeR(ash):
    exec: edgeR.R
    params:
        glm: TRUE, FALSE

DESeq2(edgeR):
    exec: DESeq2.R

jointash(ash):
    exec: jointash.R

limma(ash):
    exec: limma.R
    params:
        robust: TRUE, FALSE

score:
    exec: score.R
    params:
        data: $meta
        work_dir: $output
    return: result

DSC:
    run: (simulate, simulate_normalized, simulate_partial_null, simulate_thinning) *
         ((SVA, RUV, myrna) * (voom, quasibinom, edgeRglm, DESeq2glm) * (ash,jointash),
          (SVA, RUV, myrna) * voom * limma,
          (edgeR, DESeq2)) *
         score
    R_libs: github/stephens999/ashr, bioc/DESeq2, bioc/qvalue, mixash, github/mengyin/vash, limma,
            bioc/edgeR, RUVSeq, sva, data.table, DESeq
    exec_path: bin
    work_dir: gtex_total
    variables:
        fileName: data_path.txt
