simulate:
    level: 1
    exe: datamaker.R
    seed: R(1:50)
    params:
        path: R(gsub("[[:space:]]", "", readChar($(fileName), file.info($(fileName))$size)))
        tissue: Adipose-Subcutaneous, (Adipose-Subcutaneous, Lung)
        Nsamp: 2, 10, 50
        Ngene: 10000
        voom.normalize: TRUE
        breaksample: FALSE, TRUE
    return: data

simulate_partial_null(simulate):
    seed: R(1:5)
    params:
        tissue: (Adipose-Subcutaneous, Lung)
        breaksample: TRUE
        nullpi: 0.9

simulate_thinning(simulate):
    seed: R(1:5)
    params:
        tissue: Adipose-Subcutaneous
        breaksample: FALSE
        poisthin: TRUE

correction:
    level: 2
    exe: voom.R, quasibinom.R
    params:
        data: $1$data
        __alias__: RList(args)
    return: data

transform:
    level: 3
    exe: SVA.R, RUV.R, myrna.R, edgeRglm.R, DESeq2glm.R
    params:
        data: $*$data
        __alias__: RList(args)
    return: data

test:
    level: 4
    exe: edgeR.R, DESeq2.R, ash.R, jointash.R, limma.R
    params:
        data: $*$data
        __alias__: RList(args)
        exe[1,2]:
            glm: TRUE, FALSE
        exe[5]:
            robust: TRUE, FALSE
    return: data

score:
    exe: score.R
    params:
        data: $1
        output: $4
    return: result

DSC:
    run: (simulate, simulate_partial_null, simulate_thinning) +
         (correction + transform[1:3] + test[1:4], correction[1] + transform[1:3] + test[5],
         correction + transform[4:5] + test[3:4]) + score
    runtime:
        R_libs: github/stephens999/ashr, bioc/DESeq2, bioc/qvalue/3.2, mixash, github/mengyin/vash, limma,
                edgeR, RUVSeq, sva, data.table, DESeq
        exe_path: bin
        output: gtex_total
        variables:
            fileName: data_path.txt