language: python
python:
  - "3.7"
dist: xenial
addons:
  apt:
    update: true
    packages:
      - r-base
      - r-base-dev
      - r-cran-yaml
install:
  - pip install --ignore-installed -r requirements.txt
script:
  - python -m pip install . --no-deps -vv
  - dsc --help
  - sudo R --slave -e 'install.packages("dscrutils", repos=NULL, type="source")'
  - cd test && python test_parser.py && python test_query.py
