language: python
python:
  - "3.6"
install:
  - pip install --ignore-installed -r requirements.txt
script:
  - python -m pip install . --no-deps -vv
  - dsc --help
  - python test/test_parser.py
  - python test/test_query.py

