language:
  - python
  - r

python:
  - "3.7"

dist: xenial

addons:
  apt:
    update: true
    packages:
      - r-base
      - r-base-dev
      - r-cran-yaml

r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes
  
install:
  - pip install --ignore-installed -r requirements.txt
  
script:
  - python -m pip install . --no-deps -vv
  - dsc --help
  - dsc-query --version
  - sudo R --slave -e 'install.packages("dscrutils", repos=NULL, type="source")'
  - cd test && python test_parser.py && python test_query.py

branches:
  only:
    - master
  
