language: python

python:
  - "3.7"
  
dist: xenial

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-4.3.27.1-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set quiet yes
  - conda config --set changeps1 no
  - conda config --set auto_update_conda no
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda update --all
  - travis_retry conda install --file requirements.txt
  - conda install r-dplyr r-rlang r-ggplot2 r-shiny r-reticulate r-testthat r-yaml r-progress r-data.table r-remotes

script:
  - python -m pip install . --no-deps -vv
  - dsc --help
  - dsc-query --version
  - R CMD build --no-manual dscrutils
  - R CMD INSTALL dscrutils_*.tar.gz
  - R CMD check --as-cran --no-manual dscrutils_*.tar.gz
  - cd test && python test_parser.py && python test_query.py

branches:
  only:
    - master

