language: python

python:
  - "3.7"
  
dist: xenial

addons:
  apt:
    update: true
    packages:
      - r-base
      - r-base-dev
      - r-cran-yaml

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false

install:
  - pip install --ignore-installed -r requirements.txt

script:
  - python -m pip install . --no-deps -vv
  - dsc --help
  - dsc-query --version
  - R CMD build --no-manual dscrutils
  - sudo R CMD INSTALL dscrutils_0.3.4.tar.gz
  - R CMD check --as-cran --no-examples --no-manual dscrutils_0.3.4.tar.gz
  - cd test && python test_parser.py && python test_query.py

branches:
  only:
    - master
  
