simulate:
    level: 1
    exe: rnorm.R, rt.R
    seed: R(1:5)
    params:
        n1: 1000
        n2: 1000
        mean1: 0
        mean2: 0, 1
    return: data

transform:
    level: 2
    exe: qnorm.R
    params:
        data: {.}
    return: data

test:
    level: 2
    exe: ttest.R
    params:
        x: {.}$x
        y: {.}$y
    return: output

mse:
    exe: score.R
    params:
        data: {1}
        output: {2}
    return: result

DSC:
    scenario: simulate
    method: transform + test, test
    score: mse
    runtime:
        exe_path: .
        output: two_sample_mean