scenario:
  _exe: [R/scenarios/rnorm.R, R/scenarios/rt.R]
  n: 1000
  mean: [0, 1]
  seed: [1, 2, 3, 4, 5]
  _return: [x, mean]

method:
  _exe: [R/methods/mean.R, R/methods/median.R]
  x: $scenario.x
  _return: mean

score:
  _exe: R/scores/MSE.R
  mean_est: $method.mean
  true_mean: $scenario.mean
  _return: mse

runtime:
  lib_path:
  bin_path:
  output: simple
