simulate:
    level: 1
    exe: rnorm.R, rt.R
    seed: R(1:5)
    params:
        n: 1000
        mean: 0, 1
    return: x, mean

estimate:
    level: 2
    exe: mean.R, median.R
    params:
        x: $*$x
    return: mean

mse:
    exe: MSE.R
    params:
        mean_est: $2$mean
        true_mean: $1$mean
    return: mse

DSC:
    run: simulate *
         estimate *
         mse
    runtime:
        exe_path: R/scenarios, R/methods, R/scores
        output: one_sample_location
