scenario:
  exe: rnorm.R, rt.R
  params:
    n: 1000
    mean: 0, 1
    seed: 1, 2, 3, 4, 5
  return: x, mean

method:
  exe: mean.R, median.R
  params:
    x: %scenario.x
  return: mean

score:
  exe: MSE.R
  params:
    mean_est: %method.mean
    true_mean: %scenario.mean
  return: mse

runtime:
  exe_path: R/scenarios, R/methods, R/scores
  output: one_sample_location
