package:
  name: dsc2
  version: "0.1.0alpha"

source:
  git_url: https://github.com/stephenslab/dsc2.git
  git_rev: v0.1.0-alpha

requirements:
  build:
    - python >=3.5.1
    - setuptools
    - python >=3.5.1
    - pyyaml
    - numexpr
    - sympy
    - pandas >=0.18.0
    - rpy2 >=2.7.8
    - sos 0.5.9

  run:
    - python >=3.5.1
    - pyyaml
    - numexpr
    - sympy
    - pandas >=0.18.0
    - rpy2 >=2.7.8
    - sos 0.5.9

build:
    script: cd $RECIPE_DIR; python setup.py install

test:
  imports:
    - dsc

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/stephenslab/dsc2/wiki
  license: MIT License
  summary: 'Implementation of Dynamic Statistical Comparisons'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
