scenario:
    exe: datamaker.R
    seed: R(1:2)
    params:
        g: asis(normalmix(c(2/3,1/3),c(0,0),c(1,2))),
           asis(normalmix(rep(1/7,7),c(-1.5,-1,-0.5,0,0.5,1,1.5),rep(0.5,7)))
        min_pi0: 0
        max_pi0: 1
        nsamp: 1000
        betahatsd: 1
        __alias__: RList(args)
    return: data

method:
    exe: runash.R
    params:
        args: $scenario
    return: output

score:
    exe: score.R
    params:
        beta_true: $scenario$meta$beta
        beta_est: $method
    return: result

runtime:
    R_libs: github/stephens999/ashr
    exe_path: bin
    output: ash
