simulate:
    exe: datamaker.R
    seed: R(1:2)
    params:
        g: Asis(normalmix(c(2/3,1/3),c(0,0),c(1,2))),
           Asis(normalmix(rep(1/7,7),c(-1.5,-1,-0.5,0,0.5,1,1.5),rep(0.5,7)))
        min_pi0: 0
        max_pi0: 1
        nsamp: 1000
        betahatsd: 1
        __alias__: RList(args), true_beta = FromRList(data, meta, beta)
    return: data, true_beta

shrink:
    exe: runash.R
    params:
        args: $data
        __alias__: beta_est = FromRList(data, beta_est)
    return: data, beta_est

RMSE:
    exe: score.R
    params:
        beta_true: $true_beta
        beta_est: $beta_est
    return: result

DSC:
    run: simulate *
         shrink *
         RMSE
    runtime:
        R_libs: github/stephens999/ashr
        exe_path: bin
        output: ash
