simulate:
    exec: datamaker.R
    seed: R(1:5)
    params:
        g: Asis(ashr::normalmix(c(2/3,1/3),c(0,0),c(1,2))),
           Asis(ashr::normalmix(rep(1/7,7),c(-1.5,-1,-0.5,0,0.5,1,1.5),rep(0.5,7))),
           Asis(ashr::normalmix(c(1/4,1/4,1/3,1/6),c(-2,-1,0,1),c(2,1.5,1,1)))
        min_pi0: 0
        max_pi0: 1
        nsamp: 1000
        betahatsd: 1
        .alias: args = RList()
    return: data, true_beta = R(data$meta$beta)

shrink:
    exec: runash.R
    params:
        input: $data
        args: Asis(list(mixcompdist="normal")),
              Asis(list(mixcompdist="halfuniform"))
    return: data, beta_est = R(data$beta_est)

RMSE:
    exec: score.R
    params:
        beta_true: $true_beta
        beta_est: $beta_est
    return: result

DSC:
    run: simulate *
         shrink *
         RMSE
    R_libs: stephens999/ashr (1.0.0+)
    exec_path: bin
    output: dsc_result